---
# ------------------------------------------------------------------
#          USER-CONFIGURABLE BENCHMARK SETTINGS
# ------------------------------------------------------------------

# Define the target CUDA version the system's driver must support.
# This should match the version of the CUDA toolkit you intend to use.
# You can change this value to target a different CUDA version.
target_cuda_version: "12.5"
